language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: 4
before_script:
  - npm install -g npx
after_success:
  - npx -p node@8.9.0 -c "semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
